### ISSUE TITLE
Create a distinguished contributors group in the community forum

### ISSUE THREAD

**Issue by choldgraf** [jupyter/distinguished-contributors#2]
Hey all - I opened a topic to discuss adding a Distinguished Contributors group in the Jupyter community forum: https://discourse.jupyter.org/t/create-a-distinguished-contributor-group-badge/7036

what do folks think?

**Comment by vidartf** [comment]
Seems as if this has been done? :)

**Comment by choldgraf** [comment]
It has! You all should be added to it, let me know if I've missed somebody :-)
